/** Полный справочник стран (ISO + код). */
export const PHONE_COUNTRIES_DATA = [
  { id: 'RU', name: 'Россия', dialCode: '+7', flag: '🇷🇺', example: '10 digits', nationalLength: 10 },
  { id: 'BY', name: 'Беларусь', dialCode: '+375', flag: '🇧🇾', example: '9 digits', nationalLength: 9 },
  { id: 'KZ', name: 'Казахстан', dialCode: '+7', flag: '🇰🇿', example: '10 digits', nationalLength: 10 },
  { id: 'UA', name: 'Украина', dialCode: '+380', flag: '🇺🇦', example: '9 digits', nationalLength: 9 },
  { id: 'UZ', name: 'Узбекистан', dialCode: '+998', flag: '🇺🇿', example: '9 digits', nationalLength: 9 },
  { id: 'AM', name: 'Армения', dialCode: '+374', flag: '🇦🇲', example: '8 digits', nationalLength: 8 },
  { id: 'AZ', name: 'Азербайджан', dialCode: '+994', flag: '🇦🇿', example: '9 digits', nationalLength: 9 },
  { id: 'GE', name: 'Грузия', dialCode: '+995', flag: '🇬🇪', example: '9 digits', nationalLength: 9 },
  { id: 'KG', name: 'Киргизия', dialCode: '+996', flag: '🇰🇬', example: '9 digits', nationalLength: 9 },
  { id: 'TJ', name: 'Таджикистан', dialCode: '+992', flag: '🇹🇯', example: '9 digits', nationalLength: 9 },
  { id: 'TM', name: 'Туркменистан', dialCode: '+993', flag: '🇹🇲', example: '8 digits', nationalLength: 8 },
  { id: 'MD', name: 'Молдова', dialCode: '+373', flag: '🇲🇩', example: '8 digits', nationalLength: 8 },
  { id: 'LT', name: 'Литва', dialCode: '+370', flag: '🇱🇹', example: '8 digits', nationalLength: 8 },
  { id: 'LV', name: 'Латвия', dialCode: '+371', flag: '🇱🇻', example: '8 digits', nationalLength: 8 },
  { id: 'EE', name: 'Эстония', dialCode: '+372', flag: '🇪🇪', example: '8 digits', nationalLength: 8 },
  { id: 'DE', name: 'Германия', dialCode: '+49', flag: '🇩🇪', example: '11 digits', nationalLength: 11 },
  { id: 'TR', name: 'Турция', dialCode: '+90', flag: '🇹🇷', example: '10 digits', nationalLength: 10 },
  { id: 'US', name: 'США', dialCode: '+1', flag: '🇺🇸', example: '10 digits', nationalLength: 10 },
  { id: 'GB', name: 'Великобритания', dialCode: '+44', flag: '🇬🇧', example: '10 digits', nationalLength: 10 },
  { id: 'CN', name: 'Китай', dialCode: '+86', flag: '🇨🇳', example: '11 digits', nationalLength: 11 },
  { id: 'AE', name: 'ОАЭ', dialCode: '+971', flag: '🇦🇪', example: '9 digits', nationalLength: 9 },
  { id: 'IL', name: 'Израиль', dialCode: '+972', flag: '🇮🇱', example: '9 digits', nationalLength: 9 },
  { id: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', example: '9 digits', nationalLength: 9 },
  { id: 'AL', name: 'Albania', dialCode: '+355', flag: '🇦🇱', example: '9 digits', nationalLength: 9 },
  { id: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿', example: '9 digits', nationalLength: 9 },
  { id: 'AS', name: 'American Samoa', dialCode: '+1684', flag: '🇦🇸', example: '10 digits', nationalLength: 10 },
  { id: 'AD', name: 'Andorra', dialCode: '+376', flag: '🇦🇩', example: '9 digits', nationalLength: 9 },
  { id: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴', example: '9 digits', nationalLength: 9 },
  { id: 'AI', name: 'Anguilla', dialCode: '+1264', flag: '🇦🇮', example: '10 digits', nationalLength: 10 },
  { id: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268', flag: '🇦🇬', example: '10 digits', nationalLength: 10 },
  { id: 'AR', name: 'Аргентина', dialCode: '+54', flag: '🇦🇷', example: '10 digits', nationalLength: 10 },
  { id: 'AW', name: 'Aruba', dialCode: '+297', flag: '🇦🇼', example: '7 digits', nationalLength: 7 },
  { id: 'AU', name: 'Австралия', dialCode: '+61', flag: '🇦🇺', example: '9 digits', nationalLength: 9 },
  { id: 'AT', name: 'Австрия', dialCode: '+43', flag: '🇦🇹', example: '10 digits', nationalLength: 10 },
  { id: 'BS', name: 'Bahamas', dialCode: '+1242', flag: '🇧🇸', example: '10 digits', nationalLength: 10 },
  { id: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭', example: '8 digits', nationalLength: 8 },
  { id: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', example: '10 digits', nationalLength: 10 },
  { id: 'BB', name: 'Barbados', dialCode: '+1246', flag: '🇧🇧', example: '10 digits', nationalLength: 10 },
  { id: 'BE', name: 'Бельгия', dialCode: '+32', flag: '🇧🇪', example: '9 digits', nationalLength: 9 },
  { id: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿', example: '7 digits', nationalLength: 7 },
  { id: 'BJ', name: 'Benin', dialCode: '+229', flag: '🇧🇯', example: '8 digits', nationalLength: 8 },
  { id: 'BM', name: 'Bermuda', dialCode: '+1441', flag: '🇧🇲', example: '10 digits', nationalLength: 10 },
  { id: 'BT', name: 'Bhutan', dialCode: '+975', flag: '🇧🇹', example: '8 digits', nationalLength: 8 },
  { id: 'BO', name: 'Bolivia', dialCode: '+591', flag: '🇧🇴', example: '8 digits', nationalLength: 8 },
  { id: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦', example: '8 digits', nationalLength: 8 },
  { id: 'BW', name: 'Botswana', dialCode: '+267', flag: '🇧🇼', example: '8 digits', nationalLength: 8 },
  { id: 'BR', name: 'Бразилия', dialCode: '+55', flag: '🇧🇷', example: '11 digits', nationalLength: 11 },
  { id: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳', example: '7 digits', nationalLength: 7 },
  { id: 'BG', name: 'Болгария', dialCode: '+359', flag: '🇧🇬', example: '9 digits', nationalLength: 9 },
  { id: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫', example: '8 digits', nationalLength: 8 },
  { id: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮', example: '8 digits', nationalLength: 8 },
  { id: 'KH', name: 'Cambodia', dialCode: '+855', flag: '🇰🇭', example: '9 digits', nationalLength: 9 },
  { id: 'CM', name: 'Cameroon', dialCode: '+237', flag: '🇨🇲', example: '9 digits', nationalLength: 9 },
  { id: 'CA', name: 'Канада', dialCode: '+1', flag: '🇨🇦', example: '10 digits', nationalLength: 10 },
  { id: 'CV', name: 'Cape Verde', dialCode: '+238', flag: '🇨🇻', example: '7 digits', nationalLength: 7 },
  { id: 'KY', name: 'Cayman Islands', dialCode: '+1345', flag: '🇰🇾', example: '10 digits', nationalLength: 10 },
  { id: 'CF', name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫', example: '8 digits', nationalLength: 8 },
  { id: 'TD', name: 'Chad', dialCode: '+235', flag: '🇹🇩', example: '8 digits', nationalLength: 8 },
  { id: 'CL', name: 'Chile', dialCode: '+56', flag: '🇨🇱', example: '9 digits', nationalLength: 9 },
  { id: 'CO', name: 'Colombia', dialCode: '+57', flag: '🇨🇴', example: '10 digits', nationalLength: 10 },
  { id: 'KM', name: 'Comoros', dialCode: '+269', flag: '🇰🇲', example: '7 digits', nationalLength: 7 },
  { id: 'CG', name: 'Congo', dialCode: '+242', flag: '🇨🇬', example: '9 digits', nationalLength: 9 },
  { id: 'CD', name: 'Congo (DRC)', dialCode: '+243', flag: '🇨🇩', example: '9 digits', nationalLength: 9 },
  { id: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', example: '8 digits', nationalLength: 8 },
  { id: 'CI', name: 'Cote d\'Ivoire', dialCode: '+225', flag: '🇨🇮', example: '8 digits', nationalLength: 8 },
  { id: 'HR', name: 'Croatia', dialCode: '+385', flag: '🇭🇷', example: '9 digits', nationalLength: 9 },
  { id: 'CU', name: 'Cuba', dialCode: '+53', flag: '🇨🇺', example: '8 digits', nationalLength: 8 },
  { id: 'CY', name: 'Cyprus', dialCode: '+357', flag: '🇨🇾', example: '8 digits', nationalLength: 8 },
  { id: 'CZ', name: 'Чехия', dialCode: '+420', flag: '🇨🇿', example: '9 digits', nationalLength: 9 },
  { id: 'DK', name: 'Дания', dialCode: '+45', flag: '🇩🇰', example: '8 digits', nationalLength: 8 },
  { id: 'DJ', name: 'Djibouti', dialCode: '+253', flag: '🇩🇯', example: '8 digits', nationalLength: 8 },
  { id: 'DM', name: 'Dominica', dialCode: '+1767', flag: '🇩🇲', example: '10 digits', nationalLength: 10 },
  { id: 'DO', name: 'Dominican Republic', dialCode: '+1809', flag: '🇩🇴', example: '10 digits', nationalLength: 10 },
  { id: 'EC', name: 'Ecuador', dialCode: '+593', flag: '🇪🇨', example: '9 digits', nationalLength: 9 },
  { id: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬', example: '10 digits', nationalLength: 10 },
  { id: 'SV', name: 'El Salvador', dialCode: '+503', flag: '🇸🇻', example: '8 digits', nationalLength: 8 },
  { id: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶', example: '9 digits', nationalLength: 9 },
  { id: 'ER', name: 'Eritrea', dialCode: '+291', flag: '🇪🇷', example: '7 digits', nationalLength: 7 },
  { id: 'SZ', name: 'Eswatini', dialCode: '+268', flag: '🇸🇿', example: '8 digits', nationalLength: 8 },
  { id: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹', example: '9 digits', nationalLength: 9 },
  { id: 'FJ', name: 'Fiji', dialCode: '+679', flag: '🇫🇯', example: '7 digits', nationalLength: 7 },
  { id: 'FI', name: 'Финляндия', dialCode: '+358', flag: '🇫🇮', example: '10 digits', nationalLength: 10 },
  { id: 'FR', name: 'Франция', dialCode: '+33', flag: '🇫🇷', example: '9 digits', nationalLength: 9 },
  { id: 'GF', name: 'French Guiana', dialCode: '+594', flag: '🇬🇫', example: '9 digits', nationalLength: 9 },
  { id: 'PF', name: 'French Polynesia', dialCode: '+689', flag: '🇵🇫', example: '8 digits', nationalLength: 8 },
  { id: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦', example: '8 digits', nationalLength: 8 },
  { id: 'GM', name: 'Gambia', dialCode: '+220', flag: '🇬🇲', example: '7 digits', nationalLength: 7 },
  { id: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', example: '9 digits', nationalLength: 9 },
  { id: 'GI', name: 'Gibraltar', dialCode: '+350', flag: '🇬🇮', example: '8 digits', nationalLength: 8 },
  { id: 'GR', name: 'Греция', dialCode: '+30', flag: '🇬🇷', example: '10 digits', nationalLength: 10 },
  { id: 'GL', name: 'Greenland', dialCode: '+299', flag: '🇬🇱', example: '6 digits', nationalLength: 6 },
  { id: 'GD', name: 'Grenada', dialCode: '+1473', flag: '🇬🇩', example: '10 digits', nationalLength: 10 },
  { id: 'GP', name: 'Guadeloupe', dialCode: '+590', flag: '🇬🇵', example: '9 digits', nationalLength: 9 },
  { id: 'GU', name: 'Guam', dialCode: '+1671', flag: '🇬🇺', example: '10 digits', nationalLength: 10 },
  { id: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹', example: '8 digits', nationalLength: 8 },
  { id: 'GN', name: 'Guinea', dialCode: '+224', flag: '🇬🇳', example: '9 digits', nationalLength: 9 },
  { id: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼', example: '9 digits', nationalLength: 9 },
  { id: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾', example: '7 digits', nationalLength: 7 },
  { id: 'HT', name: 'Haiti', dialCode: '+509', flag: '🇭🇹', example: '8 digits', nationalLength: 8 },
  { id: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳', example: '8 digits', nationalLength: 8 },
  { id: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰', example: '8 digits', nationalLength: 8 },
  { id: 'HU', name: 'Венгрия', dialCode: '+36', flag: '🇭🇺', example: '9 digits', nationalLength: 9 },
  { id: 'IS', name: 'Iceland', dialCode: '+354', flag: '🇮🇸', example: '7 digits', nationalLength: 7 },
  { id: 'IN', name: 'Индия', dialCode: '+91', flag: '🇮🇳', example: '10 digits', nationalLength: 10 },
  { id: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', example: '10 digits', nationalLength: 10 },
  { id: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷', example: '10 digits', nationalLength: 10 },
  { id: 'IQ', name: 'Iraq', dialCode: '+964', flag: '🇮🇶', example: '10 digits', nationalLength: 10 },
  { id: 'IE', name: 'Ирландия', dialCode: '+353', flag: '🇮🇪', example: '9 digits', nationalLength: 9 },
  { id: 'IT', name: 'Италия', dialCode: '+39', flag: '🇮🇹', example: '10 digits', nationalLength: 10 },
  { id: 'JM', name: 'Jamaica', dialCode: '+1876', flag: '🇯🇲', example: '10 digits', nationalLength: 10 },
  { id: 'JP', name: 'Япония', dialCode: '+81', flag: '🇯🇵', example: '10 digits', nationalLength: 10 },
  { id: 'JO', name: 'Jordan', dialCode: '+962', flag: '🇯🇴', example: '9 digits', nationalLength: 9 },
  { id: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', example: '9 digits', nationalLength: 9 },
  { id: 'KI', name: 'Kiribati', dialCode: '+686', flag: '🇰🇮', example: '8 digits', nationalLength: 8 },
  { id: 'XK', name: 'Kosovo', dialCode: '+383', flag: '🇽🇰', example: '8 digits', nationalLength: 8 },
  { id: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼', example: '8 digits', nationalLength: 8 },
  { id: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦', example: '10 digits', nationalLength: 10 },
  { id: 'LB', name: 'Lebanon', dialCode: '+961', flag: '🇱🇧', example: '8 digits', nationalLength: 8 },
  { id: 'LS', name: 'Lesotho', dialCode: '+266', flag: '🇱🇸', example: '8 digits', nationalLength: 8 },
  { id: 'LR', name: 'Liberia', dialCode: '+231', flag: '🇱🇷', example: '8 digits', nationalLength: 8 },
  { id: 'LY', name: 'Libya', dialCode: '+218', flag: '🇱🇾', example: '9 digits', nationalLength: 9 },
  { id: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮', example: '7 digits', nationalLength: 7 },
  { id: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', example: '9 digits', nationalLength: 9 },
  { id: 'MO', name: 'Macao', dialCode: '+853', flag: '🇲🇴', example: '8 digits', nationalLength: 8 },
  { id: 'MG', name: 'Madagascar', dialCode: '+261', flag: '🇲🇬', example: '9 digits', nationalLength: 9 },
  { id: 'MW', name: 'Malawi', dialCode: '+265', flag: '🇲🇼', example: '9 digits', nationalLength: 9 },
  { id: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', example: '9 digits', nationalLength: 9 },
  { id: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻', example: '7 digits', nationalLength: 7 },
  { id: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱', example: '8 digits', nationalLength: 8 },
  { id: 'MT', name: 'Malta', dialCode: '+356', flag: '🇲🇹', example: '8 digits', nationalLength: 8 },
  { id: 'MH', name: 'Marshall Islands', dialCode: '+692', flag: '🇲🇭', example: '7 digits', nationalLength: 7 },
  { id: 'MQ', name: 'Martinique', dialCode: '+596', flag: '🇲🇶', example: '9 digits', nationalLength: 9 },
  { id: 'MR', name: 'Mauritania', dialCode: '+222', flag: '🇲🇷', example: '8 digits', nationalLength: 8 },
  { id: 'MU', name: 'Mauritius', dialCode: '+230', flag: '🇲🇺', example: '8 digits', nationalLength: 8 },
  { id: 'MX', name: 'Мексика', dialCode: '+52', flag: '🇲🇽', example: '10 digits', nationalLength: 10 },
  { id: 'FM', name: 'Micronesia', dialCode: '+691', flag: '🇫🇲', example: '7 digits', nationalLength: 7 },
  { id: 'MC', name: 'Monaco', dialCode: '+377', flag: '🇲🇨', example: '8 digits', nationalLength: 8 },
  { id: 'MN', name: 'Mongolia', dialCode: '+976', flag: '🇲🇳', example: '8 digits', nationalLength: 8 },
  { id: 'ME', name: 'Montenegro', dialCode: '+382', flag: '🇲🇪', example: '8 digits', nationalLength: 8 },
  { id: 'MS', name: 'Montserrat', dialCode: '+1664', flag: '🇲🇸', example: '10 digits', nationalLength: 10 },
  { id: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦', example: '9 digits', nationalLength: 9 },
  { id: 'MZ', name: 'Mozambique', dialCode: '+258', flag: '🇲🇿', example: '9 digits', nationalLength: 9 },
  { id: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', example: '9 digits', nationalLength: 9 },
  { id: 'NA', name: 'Namibia', dialCode: '+264', flag: '🇳🇦', example: '9 digits', nationalLength: 9 },
  { id: 'NR', name: 'Nauru', dialCode: '+674', flag: '🇳🇷', example: '7 digits', nationalLength: 7 },
  { id: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵', example: '10 digits', nationalLength: 10 },
  { id: 'NL', name: 'Нидерланды', dialCode: '+31', flag: '🇳🇱', example: '9 digits', nationalLength: 9 },
  { id: 'NC', name: 'New Caledonia', dialCode: '+687', flag: '🇳🇨', example: '6 digits', nationalLength: 6 },
  { id: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿', example: '9 digits', nationalLength: 9 },
  { id: 'NI', name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮', example: '8 digits', nationalLength: 8 },
  { id: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪', example: '8 digits', nationalLength: 8 },
  { id: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', example: '10 digits', nationalLength: 10 },
  { id: 'NU', name: 'Niue', dialCode: '+683', flag: '🇳🇺', example: '4 digits', nationalLength: 4 },
  { id: 'NF', name: 'Norfolk Island', dialCode: '+672', flag: '🇳🇫', example: '6 digits', nationalLength: 6 },
  { id: 'KP', name: 'North Korea', dialCode: '+850', flag: '🇰🇵', example: '10 digits', nationalLength: 10 },
  { id: 'MK', name: 'North Macedonia', dialCode: '+389', flag: '🇲🇰', example: '8 digits', nationalLength: 8 },
  { id: 'NO', name: 'Норвегия', dialCode: '+47', flag: '🇳🇴', example: '8 digits', nationalLength: 8 },
  { id: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲', example: '8 digits', nationalLength: 8 },
  { id: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', example: '10 digits', nationalLength: 10 },
  { id: 'PW', name: 'Palau', dialCode: '+680', flag: '🇵🇼', example: '7 digits', nationalLength: 7 },
  { id: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸', example: '9 digits', nationalLength: 9 },
  { id: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦', example: '8 digits', nationalLength: 8 },
  { id: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬', example: '8 digits', nationalLength: 8 },
  { id: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', example: '9 digits', nationalLength: 9 },
  { id: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪', example: '9 digits', nationalLength: 9 },
  { id: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', example: '10 digits', nationalLength: 10 },
  { id: 'PL', name: 'Польша', dialCode: '+48', flag: '🇵🇱', example: '9 digits', nationalLength: 9 },
  { id: 'PT', name: 'Португалия', dialCode: '+351', flag: '🇵🇹', example: '9 digits', nationalLength: 9 },
  { id: 'PR', name: 'Puerto Rico', dialCode: '+1787', flag: '🇵🇷', example: '10 digits', nationalLength: 10 },
  { id: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', example: '8 digits', nationalLength: 8 },
  { id: 'RE', name: 'Reunion', dialCode: '+262', flag: '🇷🇪', example: '9 digits', nationalLength: 9 },
  { id: 'RO', name: 'Румыния', dialCode: '+40', flag: '🇷🇴', example: '9 digits', nationalLength: 9 },
  { id: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', example: '9 digits', nationalLength: 9 },
  { id: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869', flag: '🇰🇳', example: '10 digits', nationalLength: 10 },
  { id: 'LC', name: 'Saint Lucia', dialCode: '+1758', flag: '🇱🇨', example: '10 digits', nationalLength: 10 },
  { id: 'VC', name: 'Saint Vincent', dialCode: '+1784', flag: '🇻🇨', example: '10 digits', nationalLength: 10 },
  { id: 'WS', name: 'Samoa', dialCode: '+685', flag: '🇼🇸', example: '7 digits', nationalLength: 7 },
  { id: 'SM', name: 'San Marino', dialCode: '+378', flag: '🇸🇲', example: '10 digits', nationalLength: 10 },
  { id: 'ST', name: 'Sao Tome and Principe', dialCode: '+239', flag: '🇸🇹', example: '7 digits', nationalLength: 7 },
  { id: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦', example: '9 digits', nationalLength: 9 },
  { id: 'SN', name: 'Senegal', dialCode: '+221', flag: '🇸🇳', example: '9 digits', nationalLength: 9 },
  { id: 'RS', name: 'Serbia', dialCode: '+381', flag: '🇷🇸', example: '9 digits', nationalLength: 9 },
  { id: 'SC', name: 'Seychelles', dialCode: '+248', flag: '🇸🇨', example: '7 digits', nationalLength: 7 },
  { id: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱', example: '8 digits', nationalLength: 8 },
  { id: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬', example: '8 digits', nationalLength: 8 },
  { id: 'SX', name: 'Sint Maarten', dialCode: '+1721', flag: '🇸🇽', example: '10 digits', nationalLength: 10 },
  { id: 'SK', name: 'Словакия', dialCode: '+421', flag: '🇸🇰', example: '9 digits', nationalLength: 9 },
  { id: 'SI', name: 'Slovenia', dialCode: '+386', flag: '🇸🇮', example: '8 digits', nationalLength: 8 },
  { id: 'SB', name: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧', example: '7 digits', nationalLength: 7 },
  { id: 'SO', name: 'Somalia', dialCode: '+252', flag: '🇸🇴', example: '8 digits', nationalLength: 8 },
  { id: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦', example: '9 digits', nationalLength: 9 },
  { id: 'KR', name: 'Южная Корея', dialCode: '+82', flag: '🇰🇷', example: '10 digits', nationalLength: 10 },
  { id: 'SS', name: 'South Sudan', dialCode: '+211', flag: '🇸🇸', example: '9 digits', nationalLength: 9 },
  { id: 'ES', name: 'Испания', dialCode: '+34', flag: '🇪🇸', example: '9 digits', nationalLength: 9 },
  { id: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', example: '9 digits', nationalLength: 9 },
  { id: 'SD', name: 'Sudan', dialCode: '+249', flag: '🇸🇩', example: '9 digits', nationalLength: 9 },
  { id: 'SR', name: 'Suriname', dialCode: '+597', flag: '🇸🇷', example: '7 digits', nationalLength: 7 },
  { id: 'SE', name: 'Швеция', dialCode: '+46', flag: '🇸🇪', example: '9 digits', nationalLength: 9 },
  { id: 'CH', name: 'Швейцария', dialCode: '+41', flag: '🇨🇭', example: '9 digits', nationalLength: 9 },
  { id: 'SY', name: 'Syria', dialCode: '+963', flag: '🇸🇾', example: '9 digits', nationalLength: 9 },
  { id: 'TW', name: 'Taiwan', dialCode: '+886', flag: '🇹🇼', example: '9 digits', nationalLength: 9 },
  { id: 'TZ', name: 'Tanzania', dialCode: '+255', flag: '🇹🇿', example: '9 digits', nationalLength: 9 },
  { id: 'TH', name: 'Thailand', dialCode: '+66', flag: '🇹🇭', example: '9 digits', nationalLength: 9 },
  { id: 'TL', name: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱', example: '8 digits', nationalLength: 8 },
  { id: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬', example: '8 digits', nationalLength: 8 },
  { id: 'TO', name: 'Tonga', dialCode: '+676', flag: '🇹🇴', example: '7 digits', nationalLength: 7 },
  { id: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', flag: '🇹🇹', example: '10 digits', nationalLength: 10 },
  { id: 'TN', name: 'Tunisia', dialCode: '+216', flag: '🇹🇳', example: '8 digits', nationalLength: 8 },
  { id: 'TC', name: 'Turks and Caicos', dialCode: '+1649', flag: '🇹🇨', example: '10 digits', nationalLength: 10 },
  { id: 'TV', name: 'Tuvalu', dialCode: '+688', flag: '🇹🇻', example: '6 digits', nationalLength: 6 },
  { id: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬', example: '9 digits', nationalLength: 9 },
  { id: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', example: '8 digits', nationalLength: 8 },
  { id: 'VU', name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺', example: '7 digits', nationalLength: 7 },
  { id: 'VA', name: 'Vatican City', dialCode: '+39', flag: '🇻🇦', example: '10 digits', nationalLength: 10 },
  { id: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪', example: '10 digits', nationalLength: 10 },
  { id: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', example: '9 digits', nationalLength: 9 },
  { id: 'VG', name: 'Virgin Islands (UK)', dialCode: '+1284', flag: '🇻🇬', example: '10 digits', nationalLength: 10 },
  { id: 'VI', name: 'Virgin Islands (US)', dialCode: '+1340', flag: '🇻🇮', example: '10 digits', nationalLength: 10 },
  { id: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪', example: '9 digits', nationalLength: 9 },
  { id: 'ZM', name: 'Zambia', dialCode: '+260', flag: '🇿🇲', example: '9 digits', nationalLength: 9 },
  { id: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', example: '9 digits', nationalLength: 9 },
];
